version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - "9027:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:7.0.8
    restart: always
    env_file:
      - .env.db
    # volumes:
    #   - ./data:/data/db